apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: graildient-descent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: graildient-descent-api:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "python",
              "-m",
              "uvicorn",
              "api.main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
            ]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: DATABASE_URL
            - name: S3_MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: S3_MODEL_PATH
            - name: S3_MODELS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: S3_MODELS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: AWS_REGION
            - name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: AWS_ENDPOINT_URL
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: graildient-descent
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
