apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: graildient-descent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: graildient-descent-api:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "python",
              "-m",
              "uvicorn",
              "api.main:app",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
            ]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres:5432/graildient_stats"
            - name: S3_MODEL_PATH
              value: "benchmarks/catboost_v1.pkl"
            - name: S3_MODELS_BUCKET
              value: "graildient-models"
            - name: AWS_REGION
              value: "ru-central1"
            - name: AWS_ENDPOINT_URL
              value: "https://storage.yandexcloud.net"
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
          resources:
            limits:
              memory: "2Gi" # Increase from 1Gi to 2Gi
              cpu: "500m"
            requests:
              memory: "1Gi" # Increase from 512Mi to 1Gi
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: graildient-descent
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
