apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: graildient-descent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: graildient-descent-celery:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "celery",
              "-A",
              "celery_tasks.worker",
              "worker",
              "--loglevel=info",
              "--concurrency=2",
            ]
          env:
            - name: PYTHONPATH
              value: "/code"
            - name: S3_MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: S3_MODEL_PATH
            - name: S3_MODELS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: S3_MODELS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: AWS_REGION
            - name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: AWS_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: CELERY_RESULT_BACKEND
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
