apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  namespace: graildient-descent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower
  template:
    metadata:
      labels:
        app: celery-flower
    spec:
      containers:
        - name: celery-flower
          image: mher/flower
          ports:
            - containerPort: 5555
          env:
            - name: FLOWER_PORT
              value: "5555"
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: graildient-descent-config
                  key: CELERY_BROKER_URL
            - name: FLOWER_URL_PREFIX
              value: "flower"
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: celery-flower
  namespace: graildient-descent
spec:
  selector:
    app: celery-flower
  ports:
    - port: 5555
      targetPort: 5555
  type: ClusterIP
