apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: graildient-descent
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - graildient-descent
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: node-exporter
            action: keep

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq-exporter:9419']

      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter:9187']

      - job_name: 'api'
        metrics_path: /api/metrics
        static_configs:
          - targets: ['api:8000']
