apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: graildient-descent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: graildient-descent-streamlit:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "streamlit",
              "run",
              "streamlit_app/app.py",
              "--server.port=8501",
              "--server.address=0.0.0.0",
            ]
          ports:
            - containerPort: 8501
          env:
            - name: PYTHONPATH
              value: "/code"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: API_BASE_URL
              value: "http://api:8000"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: graildient-descent
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
